export const LOGGED_USER = 'LOGGED_USER';
export const ERROR_IN_LOGIN = 'ERROR_IN_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ERROR_IN_REGISTER = 'ERROR_IN_REGISTER';
export const UPDATED_USER = 'UPDATED_USER';
export const ERROR_IN_UPDATE_USER = 'ERROR_IN_UPDATE_USER';
export const ERROR_IN_DELETE_USER = 'ERROR_IN_DELETE_USER';
