// sign up
export const ACCOUNT_SUCCESSFULLY_CREATED = 'ACCOUNT_SUCCESSFULLY_CREATED';
export const ERROR_CREATING_ACCOUNT = 'ERROR_CREATING_ACCOUNT';

// sign in
export const USER_SUCCESSFULLY_SIGNED_IN = 'USER_SUCCESSFULLY_SIGNED_IN';
export const ERROR_NO_USERS_FOUND = 'ERROR_NO_USERS_FOUND';
export const ERROR_WRONG_ACCOUNT_DATA = 'ERROR_WRONG_ACCOUNT_DATA';

// sign in/up
export const RESET_USER_STATE = 'RESET_USER_STATE';
