export const ACCOUNT_SUCCESSFULLY_CREATED = 'ACCOUNT_SUCCESSFULLY_CREATED';
export const ERROR_CREATING_ACCOUNT = 'ERROR_CREATING_ACCOUNT';

export const USER_SUCCESSFULLY_SIGNED_IN = 'USER_SUCCESSFULLY_SIGNED_IN';
export const ERROR_NO_USERS_FOUND = 'ERROR_NO_USERS_FOUND';
export const ERROR_WRONG_ACCOUNT_DATA = 'ERROR_WRONG_ACCOUNT_DATA';

export const LOG_OUT_USER = 'LOG_OUT_USER';

export const RE_SIGN_IN = 'RE_SIGN_IN';

export const AVATAR_CHANGED = 'AVATAR_CHANGED';
