export const RECIPE_INFORMATION_FOUND = 'RECIPE_INFORMATION_FOUND';
export const RECIPE_INFORMATION_NOT_FOUND = 'RECIPE_INFORMATION_NOT_FOUND';
export const CLEAR_RECIPE_INFORMATION = 'CLEAR_RECIPE_INFORMATION';
