export const RECIPE_INFORMATION_FOUND = 'RECIPE_INFORMATION_FOUND';
export const RECIPE_INFORMATION_NOT_FOUND = 'RECIPE_INFORMATION_NOT_FOUND';
export const CLEAR_RECIPE_INFORMATION = 'CLEAR_RECIPE_INFORMATION';

export const USER_RECIPE_FETCHED = 'USER_RECIPE_FETCHED';
export const USER_RECIPE_FAILURE_AT_FETCH = 'USER_RECIPE_FAILURE_AT_FETCH';
